name: OCaml CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache OPAM
      uses: actions/cache@v2
      with:
        path: ~/.opam
        key: ${{ runner.os }}-opam-${{ hashFiles('**/opam') }}
        restore-keys: |
          ${{ runner.os }}-opam-

    - name: Install OCaml and Opam
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: '4.14.0'
        opam-repositories: |
          default
          ocaml/opam-repository

    - name: Initialise OPAM and install dependencies
      run: |
        opam init --disable-sandboxing --yes
        eval $(opam env)
        opam update
        opam install . --deps-only --yes

    - name: Build project
      run: |
        eval $(opam env)
        dune build

    - name: Run tests
      run: |
        eval $(opam env)
        dune runtest

