name: OCaml CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0  # Указан поддерживаемый параметр вместо ocaml-version
          opam-disable-sandboxing: true  # Опция для отключения sandboxing

      - name: Cache opam
        id: cache-opam
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-${{ hashFiles('**/*.opam.locked') }}
          restore-keys: |
            ${{ runner.os }}-opam-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap darcs g++-multilib gcc-multilib musl-tools
          opam install dune -y

      - name: Initialize opam and set up repositories
        run: |
          opam init --bare -a
          opam repository set-url default https://opam.ocaml.org
          opam update
        shell: bash

      - name: Install dependencies from lock file
        run: opam install . --deps-only -y
        shell: bash

      - name: Build project
        run: dune build
        shell: bash

      - name: Run tests
        run: dune runtest
        shell: bash
